name: envoy
on: [push]

jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - run: brew update-reset "$(brew --repository)"
      - run: brew tap "$GITHUB_REPOSITORY"
      - run: brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"
      - run: brew install --verbose abolin123/core/envoy
